# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
%matplotlib inline
# Import API key
from api_keys import g_key

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
cityCSV = pd.read_csv('../output_data/cities.csv')
cityData = pd.DataFrame(cityCSV)
cityData.head()

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed
0,albany,75,US,01/28/20,86,42.60,-73.97,36.00,6.93
1,west odessa,90,US,01/28/20,65,31.84,-102.50,50.00,24.16
2,ankazobe,75,MG,01/28/20,54,-18.32,47.12,84.20,12.75
3,new norfolk,40,AU,01/28/20,63,-42.78,147.06,64.40,9.17
4,jamestown,90,US,01/28/20,86,42.10,-79.24,33.01,10.29

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
gmaps.configure(api_key=g_key)

In [4]:
location = cityData[['Latitude', 'Longitude']].astype(float)
weight = cityData['Humidity'].astype(float)

In [5]:
fig = gmaps.figure()
heatLayer = gmaps.heatmap_layer(location, weights=weight,dissipating=False, 
                             max_intensity=100,point_radius = 3)
fig.add_layer(heatLayer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [6]:
narrowed_city_df = cityData[(cityData['Max Temp'] > 70)& 
                        (cityData['Max Temp'] < 85)&
                        (cityData['Wind Speed'] < 10)&
                        (cityData['Cloudiness'] < 10)]
narrowed_city_df.count()

City          18
Cloudiness    18
Country       18
Date          18
Humidity      18
Latitude      18
Longitude     18
Max Temp      18
Wind Speed    18
dtype: int64

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [7]:
base = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

narrowed_city_df['Hotel Name'] = ""

for index, row in narrowed_city_df.iterrows():
    city = row['City']
    
    print(f'Retrieving Results for {city}...')
        
    lat = narrowed_city_df.loc[index, "Latitude"]
    lng = narrowed_city_df.loc[index, "Longitude"]
    location = f'{lat},{lng}'
    
    params = {'key': g_key,
             'location': location,
             'radius': '5000',
             'type': 'lodging'}
    
    response = requests.get(base, params=params).json()
    
    results = response['results']
    
    try:
        hotelName = results[0]['name']
        print(f'Closest hotel in {city} is {hotelName}')
        narrowed_city_df.loc[index, 'Hotel Name'] = hotelName

    except (KeyError, IndexError):
        print('Unable to locate closest hotel in {city}...skipping')
              
    print('--------------')
    
print('Data Retrieval Complete')

C:\Users\octav\AppData\Local\Continuum\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

Retrieving Results for hermanus...
Closest hotel in hermanus is Misty Waves Boutique Hotel
--------------
Retrieving Results for cape town...

C:\Users\octav\AppData\Local\Continuum\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Closest hotel in cape town is Southern Sun Waterfront Cape Town
--------------
Retrieving Results for port alfred...
Closest hotel in port alfred is The Halyards Hotel
--------------
Retrieving Results for sorong...
Closest hotel in sorong is The Waigo Hotel
--------------
Retrieving Results for chuy...
Closest hotel in chuy is Nuevo Hotel Plaza
--------------
Retrieving Results for avarua...
Closest hotel in avarua is Paradise Inn
--------------
Retrieving Results for lazaro cardenas...
Closest hotel in lazaro cardenas is Hotel Quinta Antigua
--------------
Retrieving Results for aguimes...
Closest hotel in aguimes is Hotel Villa de Aguimes
--------------
Retrieving Results for hervey bay...
Closest hotel in hervey bay is Shelly Bay Resort
--------------
Retrieving Results for kavaratti...
Closest hotel in kavaratti is Hotels in Lakshadweep Islands
--------------
Retrieving Results for asfi...
Closest hotel in asfi is Hôtel Abda
--------------
Retrieving Results for monte aprazivel...
Closest hotel in monte aprazivel is Hotel Lider
--------------
Retrieving Results for aswan...
Closest hotel in aswan is Nuba Nile
--------------
Retrieving Results for rocha...
Closest hotel in rocha is Beleza Pura B&B
--------------
Retrieving Results for srivardhan...
Closest hotel in srivardhan is Savli Resort/Hotel - Shrivardhan
--------------
Retrieving Results for hatillo...
Closest hotel in hatillo is Hotel Parador El Buen Cafe
--------------
Retrieving Results for moron...
Closest hotel in moron is Hotel Morón
--------------
Retrieving Results for treinta y tres...
Closest hotel in treinta y tres is Jardines Apart-Hotel
--------------
Data Retrieval Complete

In [8]:
narrowed_city_df.head()

,City,Cloudiness,Country,Date,Humidity,Latitude,Longitude,Max Temp,Wind Speed,Hotel Name
7,hermanus,1,ZA,01/28/20,71,-34.42,19.23,78.01,8.99,Misty Waves Boutique Hotel
20,cape town,0,ZA,01/28/20,50,-33.93,18.42,78.01,9.17,Southern Sun Waterfront Cape Town
26,port alfred,0,ZA,01/28/20,72,-33.59,26.89,73.99,5.01,The Halyards Hotel
64,sorong,0,ID,01/28/20,92,-0.88,131.25,74.86,2.66,The Waigo Hotel
81,chuy,0,UY,01/28/20,45,-33.70,-53.46,76.86,9.26,Nuevo Hotel Plaza

In [9]:
hotel_df = narrowed_city_df[["Hotel Name", "Latitude", "Longitude"]]

hotel_df = hotel_df.rename(columns = {'Latitude': 'Lat',
                                     'Longitude': 'Lng'})
hotel_df

                            Hotel Name    Lat     Lng
7           Misty Waves Boutique Hotel -34.42   19.23
20   Southern Sun Waterfront Cape Town -33.93   18.42
26                  The Halyards Hotel -33.59   26.89
64                     The Waigo Hotel  -0.88  131.25
81                   Nuevo Hotel Plaza -33.70  -53.46
88                        Paradise Inn -21.21 -159.78
131               Hotel Quinta Antigua  17.96 -102.20
180             Hotel Villa de Aguimes  27.91  -15.45
238                  Shelly Bay Resort -25.30  152.85
331      Hotels in Lakshadweep Islands  10.57   72.64
338                         Hôtel Abda  32.30   -9.24
348                        Hotel Lider -20.77  -49.71
391                          Nuba Nile  24.09   32.91
404                    Beleza Pura B&B -34.48  -54.33
412   Savli Resort/Hotel - Shrivardhan  18.03   73.02
443         Hotel Parador El Buen Cafe  18.49  -66.83
505                        Hotel Morón -34.65  -58.62
508               Jardines Apart-Hotel -33.23  -54.38

In [10]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in narrowed_city_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [15]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
info_layer = gmaps.symbol_layer(locations,
                                info_box_content = hotel_info)
fig.add_layer(markers)
fig.add_layer(info_layer)
# Display Map
fig

Figure(layout=FigureLayout(height='420px'))